analysis-paths:
- analyses
clean-targets:
- target
- dbt_packages
macro-paths:
- macros
model-paths:
- models
models:
  new_model_1:
    columns:
    - name: id
      tests:
      - not_null
      - unique
    - name: name
      tests:
      - not_null
    description: This is a new model added programmatically
  shantanudbtsnowflake:
    +materialized: view
    dim:
      +materialized: table
    src:
      +materialized: ephemeral
name: shantanudbtsnowflake
profile: shantanudbtsnowflake
seed-paths:
- seeds
snapshot-paths:
- snapshots
test-paths:
- tests
version: 1.0.0
